# Generated by Django 6.0.4 on 2026-04-19 08:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_score', models.PositiveIntegerField(default=300)),
                ('payment_history_score', models.PositiveIntegerField(default=0)),
                ('credit_utilization_score', models.PositiveIntegerField(default=0)),
                ('credit_history_length_score', models.PositiveIntegerField(default=0)),
                ('credit_mix_score', models.PositiveIntegerField(default=0)),
                ('new_credit_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('risk_category', models.CharField(max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], max_length=20)),
                ('default_probability', models.DecimalField(decimal_places=2, help_text='Probability of default in %', max_digits=5)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('negative_factors', models.JSONField(blank=True, default=list)),
                ('computed_from_accounts', models.PositiveIntegerField(default=0)),
                ('computed_from_transactions', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'borrower'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Score',
                'verbose_name_plural': 'Credit Scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('medical', 'Medical Loan'), ('home_improvement', 'Home Improvement'), ('debt_consolidation', 'Debt Consolidation'), ('agriculture', 'Agriculture Loan'), ('travel', 'Travel Loan'), ('wedding', 'Wedding Loan'), ('emergency', 'Emergency Loan'), ('startup', 'Startup Funding'), ('equipment', 'Equipment Financing')], max_length=30)),
                ('purpose', models.TextField(help_text='Purpose of the loan')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_months', models.PositiveIntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('existing_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.TextField(blank=True)),
                ('employment_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('credit_check', 'Credit Check in Progress'), ('pending_documents', 'Pending Documents'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('disbursed', 'Disbursed'), ('in_repayment', 'In Repayment'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('status_notes', models.TextField(blank=True, help_text='Internal notes about the application status')),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, max_length=100)),
                ('supporting_documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'lender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(limit_choices_to={'role': 'borrower'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('medical', 'Medical Loan'), ('home_improvement', 'Home Improvement'), ('debt_consolidation', 'Debt Consolidation'), ('agriculture', 'Agriculture Loan'), ('travel', 'Travel Loan'), ('wedding', 'Wedding Loan'), ('emergency', 'Emergency Loan'), ('startup', 'Startup Funding'), ('equipment', 'Equipment Financing')], max_length=30)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('5000'))])),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('5000'))])),
                ('min_duration_months', models.PositiveIntegerField(default=1)),
                ('max_duration_months', models.PositiveIntegerField(default=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('early_repayment_penalty', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('min_credit_score', models.PositiveIntegerField(default=300)),
                ('min_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_debt_to_income_ratio', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('collateral_description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of required documents')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('approvals_count', models.PositiveIntegerField(default=0)),
                ('lender', models.ForeignKey(limit_choices_to={'role': 'lender'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('offer_message', models.TextField(blank=True)),
                ('special_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.loanapplication')),
                ('lender', models.ForeignKey(limit_choices_to={'role': 'lender'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_offers', to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.loanproduct')),
            ],
            options={
                'verbose_name': 'Loan Offer',
                'verbose_name_plural': 'Loan Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='loans.loanproduct'),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('missed', 'Missed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['status', 'loan_type'], name='loans_loanp_status_11801a_idx'),
        ),
        migrations.AddIndex(
            model_name='loanproduct',
            index=models.Index(fields=['lender', 'status'], name='loans_loanp_lender__8c3fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['application', 'status'], name='loans_loano_applica_536f22_idx'),
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['lender', 'status'], name='loans_loano_lender__486601_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['borrower', 'status'], name='loans_loana_borrowe_db3f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status', 'created_at'], name='loans_loana_status_ffca57_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['loan_type'], name='loans_loana_loan_ty_15d4e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrepayment',
            unique_together={('application', 'installment_number')},
        ),
    ]
