# Generated by Django 6.0.4 on 2026-04-19 08:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('credit', 'Credit Card'), ('fixed_deposit', 'Fixed Deposit'), ('investment', 'Investment Account'), ('loan', 'Loan Account')], max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('consent_id', models.CharField(blank=True, max_length=200)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('linked', 'Linked'), ('syncing', 'Syncing'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='linked', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('income', 'Income/Salary'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('rent', 'Rent/Housing'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('loan', 'Loan Payment'), ('other', 'Other')], default='other', max_length=30)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user', 'status'], name='banking_ban_user_id_2e7fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_id'], name='banking_ban_bank_id_e46885_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='banking_tra_user_id_69de60_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_date'], name='banking_tra_account_62a0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='banking_tra_categor_8863fc_idx'),
        ),
    ]
